

POST http://localhost:8080/Login
Content-Type: application/json

{
    "username":"Budi",
    "password":"Hamal123"
}

###
POST http://localhost:8080/user/createUser
Content-Type: application/json

{
    "email":"Hamalsaefudin48@gmail.com",
    "password":"Hamal123",
    "username": "Budi",
    "role":"user"
}