openapi: 3.0.0
info:
  title: VehicleRent
  description: VehicleRent
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /Login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "jason@example.com"
                password:
                  type: string
                  example: "pass123"
              required:
                - email
                - password
      responses:
        "200":
          description: Success
      tags: [Authentication]
